2014-04-11 23:48:12,702 ERROR Failed to execute module
Traceback (most recent call last):
  File "/home/pi/jasper/client/brain.py", line 46, in query
    module.handle(text, self.mic, self.profile)
  File "/home/pi/jasper/client/modules/HN.py", line 111, in handle
    if profile['phone_number']:
KeyError: 'phone_number'
2014-04-11 23:49:40,579 ERROR Failed to execute module
Traceback (most recent call last):
  File "/home/pi/jasper/client/brain.py", line 46, in query
    module.handle(text, self.mic, self.profile)
  File "/home/pi/jasper/client/modules/HN.py", line 111, in handle
    if profile['phone_number']:
KeyError: 'phone_number'
2014-04-11 23:49:40,579 ERROR Failed to execute module
Traceback (most recent call last):
  File "/home/pi/jasper/client/brain.py", line 46, in query
    module.handle(text, self.mic, self.profile)
  File "/home/pi/jasper/client/modules/HN.py", line 111, in handle
    if profile['phone_number']:
KeyError: 'phone_number'
2014-04-13 22:21:04,361 ERROR Failed to execute module
Traceback (most recent call last):
  File "/home/pi/jasper/client/brain.py", line 46, in query
    module.handle(text, self.mic, self.profile)
  File "/home/pi/jasper/client/modules/Birthday.py", line 19, in handle
    oauth_access_token = profile['keys']["FB_TOKEN"]
KeyError: 'keys'
2014-04-13 22:40:33,332 ERROR Failed to execute module
Traceback (most recent call last):
  File "/home/pi/jasper/client/brain.py", line 55, in query
    module.handle(text, self.mic, self.profile)
  File "/home/pi/jasper/client/modules/Exit.py", line 5, in handle
    exit()
  File "/usr/lib/python2.7/site.py", line 374, in __call__
    raise SystemExit(code)
SystemExit: None
2014-04-13 22:41:20,762 ERROR Failed to execute module
Traceback (most recent call last):
  File "/home/pi/jasper/client/brain.py", line 55, in query
    module.handle(text, self.mic, self.profile)
  File "/home/pi/jasper/client/modules/Exit.py", line 5, in handle
    exit()
  File "/usr/lib/python2.7/site.py", line 374, in __call__
    raise SystemExit(code)
SystemExit: None
2014-04-13 22:41:20,762 ERROR Failed to execute module
Traceback (most recent call last):
  File "/home/pi/jasper/client/brain.py", line 55, in query
    module.handle(text, self.mic, self.profile)
  File "/home/pi/jasper/client/modules/Exit.py", line 5, in handle
    exit()
  File "/usr/lib/python2.7/site.py", line 374, in __call__
    raise SystemExit(code)
SystemExit: None
